DATAINT-1642: Entity Relationship Information Discovery for MSSQL Connections
naveego/plugin-pub-mssql pull request #65
Opened 2023-08-30 13:40 UTC by TerryNue

resolves [DATAINT-1642](https://aunalytics.atlassian.net/browse/DATAINT-1642?atlOrigin=eyJpIjoiNWZmMWUyNzlkMzgwNGI2YmJmOWYwYjFlNDM2ZmQ5MjEiLCJwIjoiaiJ9)

identifies and retrieves foreign key relationships between database schemas

2023-08-30 13:53 UTC, roehlerw requested changes

2023-08-30 13:53 UTC, roehlerw commented on internal/server.go
> +	query := `
this doesn't account for potentially multi-part foreign key relationships

2023-09-07 16:57 UTC, roehlerw requested changes

2023-09-07 17:50 UTC, roehlerw approved these changes

2023-09-15 12:48 UTC, roehlerw requested changes

2023-09-15 12:48 UTC, roehlerw commented on internal/server.go
> +func (s *Server) DiscoverRelatedEntities(ctx context.Context, req *pub.DiscoverRelatedEntitiesRequest) (*pub.DiscoverRelatedEntitiesResponse, error) {
Needs to be modified to loop through the input schemas on the request and only return related entities to the ones requested.

2023-09-15 14:21 UTC, g1hanna approved these changes
Looks nice! A comment from Wyatt needs to be marked as resolved (it looks like you've applied the feedback). The SQL script looks great, too!

2023-09-15 14:29 UTC, roehlerw requested changes

2023-09-15 14:29 UTC, roehlerw commented on internal/server.go
> +		parts := strings.Split(schema.GetName(), ".")
This should be based on the Id and not the Name as the user can change the Schema Name but not the Id.

You should also use the function DecomposeSafeName to decode the Schema Id into parts

2023-09-18 19:39 UTC, roehlerw approved these changes

2023-09-22 13:24 UTC, uttam028 approved these changes

2023-09-22 13:55 UTC, g1hanna approved these changes

2023-09-22 13:59 UTC, merged